Fixes

diff --git a/jjdeploy b/jjdeploy
--- a/jjdeploy
+++ b/jjdeploy
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-VERSION="0.5.0"
+VERSION="0.5.1"
 
 ### Constants
 
@@ -39,76 +39,6 @@ function sendEmail ()
 			send
 		end tell
 	end tell"
-}
-
-function upload ()
-{
-	#### Upload with Transmit
-	echo "Uploading…"
-	
-	remoteFolder=$(basename "${FTPREMOTEPATH}")
-	
-	upload_result=`osascript  -e "
-	on is_running(appName)
-		tell application \"System Events\" to (name of processes) contains appName
-	end is_running
-	
-	set wasRunning to is_running(\"Transmit\")
-
-	with timeout of 600 seconds
-	tell application \"Transmit\"
-	set SuppressAppleScriptAlerts to true
-	set suppress errors to true
-	set server to item 1 of (favorites whose name is \"${TRANSMIT_FAVNAME}\")
-		set doc to (make new document at end)
-		tell current tab of doc
-			connect to server
-			tell remote browser
-			
-				create folder named \"$remoteFolder\"
-			
-				set result to (upload item at path \"${HTMLARCHIVEPATH}\" to \"${FTPREMOTEPATH}\" with resume mode overwrite)
-				if not result then
-					return false
-				end if
-				
-				set result to (upload item at path \"${PLISTARCHIVEPATH}\" to \"${FTPREMOTEPATH}\" with resume mode overwrite)
-				if not result then
-					return false
-				end if
-				
-				set result to (upload item at path \"${IPAARCHIVEPATH}\" to \"${FTPREMOTEPATH}\" with resume mode overwrite)
-				if not result then
-					return false
-				end if
-				
-				set result to (upload item at path \"${CSSARCHIVEPATH}\" to \"${FTPREMOTEPATH}\" with resume mode overwrite)
-				if not result then
-					return false
-				end if
-				
-				set result to (upload item at path \"${ICONARCHIVEPATH}\" to \"${FTPREMOTEPATH}\" with resume mode overwrite)
-				if not result then
-					return false
-				end if
-				
-			end tell
-			close remote browser
-		end tell
-		close doc
-	if not wasRunning then
-		quit
-	end if
-	return true
-	end tell
-	end timeout"`
-	
-	if [ "$upload_result" = "false" ];
-	then
-		echo -e "${redColor} Error uplading file. Please check your FTPREMOTEPATH configuration and try again.\n${endColor}"
-		exit 1
-	fi
-	
 }
 
 if [ $# -eq 1 ] && [ $1 = "init" ];
@@ -162,10 +92,10 @@ then
 	exit 0
 fi
 
+only_upload=0
 if [ $# -eq 1 ] && [ $1 = "upload" ];
 then
-	upload
-	exit 0
+	only_upload=1
 fi
 
 if [ $# -eq 2 ] && [ $1 = "init" ] && [ $2 = "resources" ];
@@ -270,6 +200,76 @@ CSSARCHIVEPATH="$ARCHIVEPATH/css"
 ICONFILENAME="Icon.png"
 ICONARCHIVEPATH="$ARCHIVEPATH/$ICONFILENAME"
 
+if [ $only_upload -eq 1 ];
+then
+	#### Upload with Transmit
+	echo "Uploading…"
+	
+	remoteFolder=$(basename "${FTPREMOTEPATH}")
+	
+	upload_result=`osascript  -e "
+	on is_running(appName)
+		tell application \"System Events\" to (name of processes) contains appName
+	end is_running
+	
+	set wasRunning to is_running(\"Transmit\")
+
+	with timeout of 600 seconds
+	tell application \"Transmit\"
+	set SuppressAppleScriptAlerts to true
+	set suppress errors to true
+	set server to item 1 of (favorites whose name is \"${TRANSMIT_FAVNAME}\")
+		set doc to (make new document at end)
+		tell current tab of doc
+			connect to server
+			tell remote browser
+			
+				create folder named \"$remoteFolder\"
+			
+				set result to (upload item at path \"${HTMLARCHIVEPATH}\" to \"${FTPREMOTEPATH}\" with resume mode overwrite)
+				if not result then
+					return false
+				end if
+				
+				set result to (upload item at path \"${PLISTARCHIVEPATH}\" to \"${FTPREMOTEPATH}\" with resume mode overwrite)
+				if not result then
+					return false
+				end if
+				
+				set result to (upload item at path \"${IPAARCHIVEPATH}\" to \"${FTPREMOTEPATH}\" with resume mode overwrite)
+				if not result then
+					return false
+				end if
+				
+				set result to (upload item at path \"${CSSARCHIVEPATH}\" to \"${FTPREMOTEPATH}\" with resume mode overwrite)
+				if not result then
+					return false
+				end if
+				
+				set result to (upload item at path \"${ICONARCHIVEPATH}\" to \"${FTPREMOTEPATH}\" with resume mode overwrite)
+				if not result then
+					return false
+				end if
+				
+			end tell
+			close remote browser
+		end tell
+		close doc
+	if not wasRunning then
+		quit
+	end if
+	return true
+	end tell
+	end timeout"`
+	
+	if [ "$upload_result" = "false" ];
+	then
+		echo -e "${redColor} Error uplading file. Please check your FTPREMOTEPATH configuration and try again.\n${endColor}"
+		exit 1
+	fi
+	
+	exit 0
+fi
 
 ### Commands
 
