Now stops the script if no config file found

diff --git a/jjdeploy b/jjdeploy
--- a/jjdeploy
+++ b/jjdeploy
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-VERSION="0.1.2"
+VERSION="0.1.3"
 
 ### Constants
 
@@ -62,6 +62,12 @@ done
 if [ -z ${config_file} ];
 then
 config_file="${PWD}/jjdeploy.config"
+fi
+
+if [ ! -f ${config_file} ];
+then
+	echo -e "${redColor} Error: No config file found. Check your current path or use jjdeploy init to create an initial template.\n${endColor}"
+	exit 1
 fi
 
 source "${config_file}"
